# Generated by Django 4.2.19 on 2025-03-02 17:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.entry_image_file_path),
        ),
    ]
