# Generated by Django 4.2.20 on 2025-03-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_entry_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_entry_images',
            field=models.IntegerField(default=4),
        ),
    ]
