# Generated by Django 4.2.20 on 2025-03-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_entry_category_alter_entry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='address',
        ),
    ]
